/* ── Language Partial ─────────────────────────────────── */

const LANGS = {
  ko: { label: '한국어', flag: '🇰🇷' },
  en: { label: 'English', flag: '🇺🇸' },
  ja: { label: '日本語', flag: '🇯🇵' },
  zh: { label: '中文', flag: '🇨🇳' },
};

const I18N = {
  ko: {
    welcome: 'Glow Trip에 오신 것을 환영합니다',
    email: '이메일',
    password: '비밀번호',
    name: '이름',
    language: '언어',
    login: '로그인',
    signup: '회원가입',
    logout: '로그아웃',
    or: '또는',
    noAccount: '계정이 없으신가요?',
    hasAccount: '이미 계정이 있으신가요?',
    namePlaceholder: '이름을 입력하세요',
    pwPlaceholder: '8자 이상',
    searchPlaceholder: '샵 검색...',
    dateTime: '날짜 및 시간',
    requestLabel: '요청사항 (선택)',
    requestPlaceholder: '예: 민감한 피부입니다...',
    bookNow: '예약하기',
    cancel: '취소',
    goOwnerDash: '상점 대시보드로 이동',
    goAdmin: '관리자 페이지로 이동',
    navShops: '샵',
    navBookings: '예약',
    navMy: '마이',
    myBookings: '내 예약',
    myPage: '마이페이지',
    noShops: '검색 결과가 없습니다',
    noBookings: '예약 내역이 없습니다',
    menu: '메뉴',
    book: '예약',
    min: '분',
    role: '역할',
    lang: '언어',
    noName: '이름 없음',
    confirmCancel: '이 예약을 취소하시겠습니까?',
    bookingSuccess: '예약이 완료되었습니다!',
    bookingFailed: '예약에 실패했습니다',
    selectDateTime: '날짜와 시간을 선택해주세요',
    loginFailed: '로그인에 실패했습니다',
    registerFailed: '회원가입에 실패했습니다',
    fillAll: '모든 항목을 입력해주세요',
    emailPwRequired: '이메일과 비밀번호를 입력해주세요',
    pwMin8: '비밀번호는 8자 이상이어야 합니다',
    socialUnavailable: '을(를) 사용할 수 없습니다. 이메일로 로그인해주세요.',
    socialFailed: '소셜 로그인에 실패했습니다',
    lineLoginFailed: 'LINE 로그인에 실패했습니다',
    // Owner dashboard
    shopDashboard: '상점 대시보드',
    backToApp: '앱으로 이동',
    bookings: '예약 목록',
    settlement: '정산',
    all: '전체',
    pending: '대기중',
    confirmed: '확정',
    completed: '완료',
    noshow: '노쇼',
    cancelled: '취소됨',
    noBookingsOwner: '예약이 없습니다',
    noShopsRegistered: '등록된 샵이 없습니다',
    confirm: '확정',
    complete: '완료',
    noshowBtn: '노쇼',
    cancelBtn: '취소',
    aiTranslation: 'AI 번역 (한국어)',
    totalSales: '총 매출',
    settlementLabel: '정산액',
    fee: '수수료',
    amount: '금액',
    noSettlements: '정산 내역이 없습니다',
    // Phase 8: Shop & Menu management
    shopInfo: '샵 정보',
    menuManage: '메뉴 관리',
    shopName: '상호명',
    shopAddress: '주소',
    shopPhone: '전화번호',
    shopDescription: '설명',
    save: '저장',
    saved: '저장되었습니다',
    addMenu: '메뉴 추가',
    menuTitle: '메뉴명',
    menuDesc: '메뉴 설명',
    menuPrice: '가격 (원)',
    menuDuration: '소요시간 (분)',
    edit: '수정',
    delete: '삭제',
    confirmDelete: '이 메뉴를 삭제하시겠습니까?',
    menuAdded: '메뉴가 추가되었습니다',
    menuUpdated: '메뉴가 수정되었습니다',
    menuDeleted: '메뉴가 삭제되었습니다',
    noMenus: '등록된 메뉴가 없습니다',
    active: '활성',
    inactive: '비활성',
    shopImage: '샵 대표 이미지',
    menuImage: '메뉴 이미지',
    uploadImage: '이미지 업로드',
    changeImage: '이미지 변경',
    uploadFailed: '업로드에 실패했습니다',
    // Phase 10: Payment
    pay: '결제하기',
    payAmount: '결제 금액',
    cardInfo: '카드 정보',
    processing: '처리 중...',
    paymentSuccess: '결제가 완료되었습니다!',
    paymentFailed: '결제에 실패했습니다',
    paymentPending: '결제 대기 중',
    refund: '환불',
    confirmRefund: '이 예약을 환불하시겠습니까?',
    refundSuccess: '환불이 완료되었습니다',
    refundFailed: '환불에 실패했습니다',
    stripeNotReady: '결제 시스템을 불러오는 중입니다',
    noPayment: '결제 정보 없음',
    // Phase 11: Map
    mapView: '지도',
    listView: '목록',
    sortDistance: '거리순',
    sortDefault: '기본순',
    km: 'km',
    locationPermission: '위치 권한이 필요합니다',
    loadingMap: '지도를 불러오는 중...',
    // Phase 12: Reviews
    reviews: '리뷰',
    writeReview: '리뷰 작성',
    rating: '평점',
    comment: '한줄평',
    commentPlaceholder: '서비스는 어떠셨나요?',
    submitReview: '리뷰 등록',
    reviewSuccess: '리뷰가 등록되었습니다',
    reviewFailed: '리뷰 등록에 실패했습니다',
    noReviews: '리뷰가 없습니다',
    avgRating: '평균 평점',
    reviewCount: '개의 리뷰',
    // Phase 14: UI Renewal
    findBeauty: '한국에서 나만의 뷰티를 찾아보세요',
    navHome: '홈',
    navProfile: '프로필',
    allCategories: '전체',
    popularClinics: '인기 클리닉',
    recommendedShops: '추천 샵',
    fromPrice: '최저',
    cat_skincare: '스킨케어',
    cat_massage: '마사지',
    cat_facial: '페이셜',
    cat_waxing: '왁싱',
    cat_body: '바디',
    selectDate: '날짜를 선택하세요',
    dayClosed: '해당 날짜는 휴무입니다',
    noSlots: '예약 가능한 시간이 없습니다',
    bookingComplete: '예약이 확정되었습니다!',
    backToHome: '홈으로 돌아가기',
    refundPolicy: '예약 확정 후 24시간 전까지 무료 취소 가능합니다.',
    schedule: '스케줄',
    openTime: '오픈',
    closeTime: '마감',
    closed: '휴무',
    saveSchedule: '스케줄 저장',
    scheduleSaved: '스케줄이 저장되었습니다',
    favAdded: '관심 목록에 추가되었습니다',
    favRemoved: '관심 목록에서 제거되었습니다',
    // Profile
    editProfile: '프로필 수정',
    profileName: '이름',
    profilePhone: '전화번호',
    profileLang: '언어',
    profileSave: '저장',
    profileCancel: '취소',
    profileUpdated: '프로필이 수정되었습니다',
    // Favorites
    myFavorites: '관심 샵',
    noFavorites: '관심 샵이 없습니다',
    // Filter
    filterPrice: '가격대',
    filterRating: '최소 평점',
    sortNewest: '최신순',
    sortPopular: '인기순',
    sortRating: '평점순',
    sortPrice: '가격순',
    sortDistance: '거리순',
    filterApply: '필터 적용',
    filterReset: '초기화',
    priceMin: '최소 가격',
    priceMax: '최대 가격',
    sortLabel: '정렬',
    filterLabel: '필터',
    // Admin
    adminPanel: '관리자 패널',
    backToApp: '앱으로 돌아가기',
    adUsers: '사용자',
    adShops: '샵',
    adBookings: '예약',
    adSettlements: '정산',
    adStats: '통계',
    adRevenue: '매출',
    adReviews: '리뷰',
    adAllRoles: '전체 역할',
    adCustomer: '고객',
    adOwner: '원장',
    adAdmin: '관리자',
    adSearch: '검색...',
    adAll: '전체',
    adActive: '활성',
    adInactive: '비활성',
    adName: '이름',
    adEmail: '이메일',
    adRole: '역할',
    adProvider: '가입 방식',
    adCreated: '가입일',
    adAction: '조치',
    adOwnerCol: '원장',
    adAddress: '주소',
    adStatus: '상태',
    adMenu: '메뉴',
    adTime: '시간',
    adPayment: '결제',
    adAmount: '금액',
    adShopCol: '샵',
    adSales: '매출',
    adFee: '수수료',
    adPayments: '결제 건수',
    adDeactivate: '비활성화',
    adActivate: '활성화',
    adCancel: '취소',
    adAllStatus: '전체 상태',
    adPending: '대기',
    adConfirmed: '확정',
    adCompleted: '완료',
    adCancelled: '취소됨',
    adNoshow: '노쇼',
    adCancelConfirm: '이 예약을 취소하고 환불하시겠습니까?',
    adTotalSales: '총 매출',
    adTotalFee: '수수료',
    adSettlement: '정산액',
    adNoData: '데이터 없음',
    adNoSettlements: '정산 내역 없음',
    adBookingStatus: '예약 현황',
    adLast7Days: '최근 7일 예약',
    adPopularShops: '인기 샵',
    adBookingsUnit: '건',
  },
  en: {
    welcome: 'Welcome to Glow Trip',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    language: 'Language',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    or: 'OR',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    namePlaceholder: 'Your name',
    pwPlaceholder: '8+ characters',
    searchPlaceholder: 'Search shops...',
    dateTime: 'Date & Time',
    requestLabel: 'Special Requests (optional)',
    requestPlaceholder: 'e.g. I have sensitive skin...',
    bookNow: 'Book Now',
    cancel: 'Cancel',
    goOwnerDash: 'Go to Shop Dashboard',
    goAdmin: 'Go to Admin Page',
    navShops: 'Shops',
    navBookings: 'Bookings',
    navMy: 'My',
    myBookings: 'My Bookings',
    myPage: 'My Page',
    noShops: 'No shops found',
    noBookings: 'No bookings yet',
    menu: 'Menu',
    book: 'Book',
    min: 'min',
    role: 'Role',
    lang: 'Lang',
    noName: 'No name',
    confirmCancel: 'Cancel this booking?',
    bookingSuccess: 'Booking created successfully!',
    bookingFailed: 'Booking failed',
    selectDateTime: 'Please select date and time',
    loginFailed: 'Login failed',
    registerFailed: 'Registration failed',
    fillAll: 'Please fill in all fields',
    emailPwRequired: 'Email and password required',
    pwMin8: 'Password must be at least 8 characters',
    socialUnavailable: ' is not available. Please use email login.',
    socialFailed: 'Social login failed',
    lineLoginFailed: 'LINE login failed',
    shopDashboard: 'Shop Dashboard',
    backToApp: 'Back to App',
    bookings: 'Bookings',
    settlement: 'Settlement',
    all: 'All',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    noshow: 'No-show',
    cancelled: 'Cancelled',
    noBookingsOwner: 'No bookings',
    noShopsRegistered: 'No shops registered',
    confirm: 'Confirm',
    complete: 'Complete',
    noshowBtn: 'No-show',
    cancelBtn: 'Cancel',
    aiTranslation: 'AI Translation (Korean)',
    totalSales: 'Total Sales',
    settlementLabel: 'Settlement',
    fee: 'Fee',
    amount: 'Amount',
    noSettlements: 'No settlements yet',
    shopInfo: 'Shop Info',
    menuManage: 'Menu Management',
    shopName: 'Shop Name',
    shopAddress: 'Address',
    shopPhone: 'Phone',
    shopDescription: 'Description',
    save: 'Save',
    saved: 'Saved',
    addMenu: 'Add Menu',
    menuTitle: 'Menu Title',
    menuDesc: 'Description',
    menuPrice: 'Price (KRW)',
    menuDuration: 'Duration (min)',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: 'Delete this menu?',
    menuAdded: 'Menu added',
    menuUpdated: 'Menu updated',
    menuDeleted: 'Menu deleted',
    noMenus: 'No menus registered',
    active: 'Active',
    inactive: 'Inactive',
    shopImage: 'Shop Image',
    menuImage: 'Menu Image',
    uploadImage: 'Upload Image',
    changeImage: 'Change Image',
    uploadFailed: 'Upload failed',
    pay: 'Pay Now',
    payAmount: 'Payment Amount',
    cardInfo: 'Card Information',
    processing: 'Processing...',
    paymentSuccess: 'Payment completed!',
    paymentFailed: 'Payment failed',
    paymentPending: 'Payment pending',
    refund: 'Refund',
    confirmRefund: 'Refund this booking?',
    refundSuccess: 'Refund completed',
    refundFailed: 'Refund failed',
    stripeNotReady: 'Loading payment system...',
    noPayment: 'No payment info',
    mapView: 'Map',
    listView: 'List',
    sortDistance: 'By Distance',
    sortDefault: 'Default',
    km: 'km',
    locationPermission: 'Location permission required',
    loadingMap: 'Loading map...',
    // Phase 12: Reviews
    reviews: 'Reviews',
    writeReview: 'Write Review',
    rating: 'Rating',
    comment: 'Comment',
    commentPlaceholder: 'How was the service?',
    submitReview: 'Submit Review',
    reviewSuccess: 'Review submitted successfully',
    reviewFailed: 'Failed to submit review',
    noReviews: 'No reviews yet',
    avgRating: 'Average Rating',
    reviewCount: 'reviews',
    // Phase 14: UI Renewal
    findBeauty: 'Find your beauty in Korea',
    navHome: 'Home',
    navProfile: 'Profile',
    allCategories: 'All',
    popularClinics: 'Popular Clinics',
    recommendedShops: 'Recommended',
    fromPrice: 'from',
    cat_skincare: 'Skincare',
    cat_massage: 'Massage',
    cat_facial: 'Facial',
    cat_waxing: 'Waxing',
    cat_body: 'Body',
    selectDate: 'Select a date',
    dayClosed: 'Closed on this day',
    noSlots: 'No available time slots',
    bookingComplete: 'Booking Confirmed!',
    backToHome: 'Back to Home',
    refundPolicy: 'Free cancellation up to 24 hours before the confirmed booking.',
    schedule: 'Schedule',
    openTime: 'Open',
    closeTime: 'Close',
    closed: 'Closed',
    saveSchedule: 'Save Schedule',
    scheduleSaved: 'Schedule saved',
    favAdded: 'Added to favorites',
    favRemoved: 'Removed from favorites',
    // Profile
    editProfile: 'Edit Profile',
    profileName: 'Name',
    profilePhone: 'Phone',
    profileLang: 'Language',
    profileSave: 'Save',
    profileCancel: 'Cancel',
    profileUpdated: 'Profile updated',
    // Favorites
    myFavorites: 'My Favorites',
    noFavorites: 'No favorite shops yet',
    // Filter
    filterPrice: 'Price Range',
    filterRating: 'Min Rating',
    sortNewest: 'Newest',
    sortPopular: 'Popular',
    sortRating: 'Rating',
    sortPrice: 'Price',
    sortDistance: 'Distance',
    filterApply: 'Apply',
    filterReset: 'Reset',
    priceMin: 'Min Price',
    priceMax: 'Max Price',
    sortLabel: 'Sort',
    filterLabel: 'Filter',
    // Admin
    adminPanel: 'Admin Panel',
    backToApp: 'Back to App',
    adUsers: 'Users',
    adShops: 'Shops',
    adBookings: 'Bookings',
    adSettlements: 'Settlements',
    adStats: 'Stats',
    adRevenue: 'Revenue',
    adReviews: 'Reviews',
    adAllRoles: 'All Roles',
    adCustomer: 'Customer',
    adOwner: 'Owner',
    adAdmin: 'Admin',
    adSearch: 'Search...',
    adAll: 'All',
    adActive: 'Active',
    adInactive: 'Inactive',
    adName: 'Name',
    adEmail: 'Email',
    adRole: 'Role',
    adProvider: 'Provider',
    adCreated: 'Created',
    adAction: 'Action',
    adOwnerCol: 'Owner',
    adAddress: 'Address',
    adStatus: 'Status',
    adMenu: 'Menu',
    adTime: 'Time',
    adPayment: 'Payment',
    adAmount: 'Amount',
    adShopCol: 'Shop',
    adSales: 'Sales',
    adFee: 'Fee',
    adPayments: 'Payments',
    adDeactivate: 'Deactivate',
    adActivate: 'Activate',
    adCancel: 'Cancel',
    adAllStatus: 'All Status',
    adPending: 'Pending',
    adConfirmed: 'Confirmed',
    adCompleted: 'Completed',
    adCancelled: 'Cancelled',
    adNoshow: 'No-show',
    adCancelConfirm: 'Cancel this booking and refund?',
    adTotalSales: 'Total Sales',
    adTotalFee: 'Fee',
    adSettlement: 'Settlement',
    adNoData: 'No data yet',
    adNoSettlements: 'No settlements yet',
    adBookingStatus: 'Booking Status',
    adLast7Days: 'Last 7 Days Bookings',
    adPopularShops: 'Popular Shops',
    adBookingsUnit: 'bookings',
  },
  ja: {
    welcome: 'Glow Tripへようこそ',
    email: 'メール',
    password: 'パスワード',
    name: '名前',
    language: '言語',
    login: 'ログイン',
    signup: '新規登録',
    logout: 'ログアウト',
    or: 'または',
    noAccount: 'アカウントをお持ちでないですか？',
    hasAccount: 'すでにアカウントをお持ちですか？',
    namePlaceholder: 'お名前を入力',
    pwPlaceholder: '8文字以上',
    searchPlaceholder: 'ショップを検索...',
    dateTime: '日時',
    requestLabel: 'リクエスト（任意）',
    requestPlaceholder: '例：敏感肌です...',
    bookNow: '予約する',
    cancel: 'キャンセル',
    goOwnerDash: 'ショップダッシュボードへ',
    goAdmin: '管理者ページへ',
    navShops: 'ショップ',
    navBookings: '予約',
    navMy: 'マイ',
    myBookings: '予約一覧',
    myPage: 'マイページ',
    noShops: 'ショップが見つかりません',
    noBookings: '予約がありません',
    menu: 'メニュー',
    book: '予約',
    min: '分',
    role: '役割',
    lang: '言語',
    noName: '名前なし',
    confirmCancel: 'この予約をキャンセルしますか？',
    bookingSuccess: '予約が完了しました！',
    bookingFailed: '予約に失敗しました',
    selectDateTime: '日時を選択してください',
    loginFailed: 'ログインに失敗しました',
    registerFailed: '登録に失敗しました',
    fillAll: 'すべての項目を入力してください',
    emailPwRequired: 'メールとパスワードを入力してください',
    pwMin8: 'パスワードは8文字以上必要です',
    socialUnavailable: 'は利用できません。メールでログインしてください。',
    socialFailed: 'ソーシャルログインに失敗しました',
    lineLoginFailed: 'LINEログインに失敗しました',
    shopDashboard: 'ショップダッシュボード',
    backToApp: 'アプリに戻る',
    bookings: '予約一覧',
    settlement: '精算',
    all: 'すべて',
    pending: '保留中',
    confirmed: '確定',
    completed: '完了',
    noshow: 'ノーショー',
    cancelled: 'キャンセル済',
    noBookingsOwner: '予約がありません',
    noShopsRegistered: '登録されたショップがありません',
    confirm: '確定',
    complete: '完了',
    noshowBtn: 'ノーショー',
    cancelBtn: 'キャンセル',
    aiTranslation: 'AI翻訳（韓国語）',
    totalSales: '総売上',
    settlementLabel: '精算額',
    fee: '手数料',
    amount: '金額',
    noSettlements: '精算履歴がありません',
    shopInfo: 'ショップ情報',
    menuManage: 'メニュー管理',
    shopName: '店舗名',
    shopAddress: '住所',
    shopPhone: '電話番号',
    shopDescription: '説明',
    save: '保存',
    saved: '保存しました',
    addMenu: 'メニュー追加',
    menuTitle: 'メニュー名',
    menuDesc: '説明',
    menuPrice: '価格（ウォン）',
    menuDuration: '所要時間（分）',
    edit: '編集',
    delete: '削除',
    confirmDelete: 'このメニューを削除しますか？',
    menuAdded: 'メニューを追加しました',
    menuUpdated: 'メニューを更新しました',
    menuDeleted: 'メニューを削除しました',
    noMenus: '登録されたメニューがありません',
    active: '有効',
    inactive: '無効',
    shopImage: 'ショップ画像',
    menuImage: 'メニュー画像',
    uploadImage: '画像アップロード',
    changeImage: '画像変更',
    uploadFailed: 'アップロードに失敗しました',
    pay: '支払う',
    payAmount: 'お支払い金額',
    cardInfo: 'カード情報',
    processing: '処理中...',
    paymentSuccess: '支払いが完了しました！',
    paymentFailed: '支払いに失敗しました',
    paymentPending: '支払い待ち',
    refund: '��金',
    confirmRefund: 'この予約を返金しますか？',
    refundSuccess: '返金が完了しました',
    refundFailed: '返金に失敗しました',
    stripeNotReady: '決済システムを読み込み中...',
    noPayment: '決済情報なし',
    mapView: '地図',
    listView: 'リスト',
    sortDistance: '距離順',
    sortDefault: 'デフォルト',
    km: 'km',
    locationPermission: '位置情報の許可が必要です',
    loadingMap: '地図を読み込み中...',
    // Phase 12: Reviews
    reviews: 'レビュー',
    writeReview: 'レビューを書く',
    rating: '評価',
    comment: 'コメント',
    commentPlaceholder: 'サービスはいかがでしたか？',
    submitReview: 'レビューを投稿',
    reviewSuccess: 'レビューが投稿されました',
    reviewFailed: 'レビューの投稿に失敗しました',
    noReviews: 'レビューがありません',
    avgRating: '平均評価',
    reviewCount: '件のレビュー',
    // Phase 14: UI Renewal
    findBeauty: '韓国であなたの美を見つけよう',
    navHome: 'ホーム',
    navProfile: 'プロフィール',
    allCategories: 'すべて',
    popularClinics: '人気クリニック',
    recommendedShops: 'おすすめ',
    fromPrice: '最低',
    cat_skincare: 'スキンケア',
    cat_massage: 'マッサージ',
    cat_facial: 'フェイシャル',
    cat_waxing: 'ワックス',
    cat_body: 'ボディ',
    selectDate: '日付を選択してください',
    dayClosed: 'この日は定休日です',
    noSlots: '予約可能な時間がありません',
    bookingComplete: '予約が確定しました！',
    backToHome: 'ホームに戻る',
    refundPolicy: '確定後24時間前まで無料キャンセル可能です。',
    schedule: 'スケジュール',
    openTime: '開店',
    closeTime: '閉店',
    closed: '休み',
    saveSchedule: 'スケジュール保存',
    scheduleSaved: 'スケジュールが保存されました',
    favAdded: 'お気に入りに追加しました',
    favRemoved: 'お気に入りから削除しました',
    // Profile
    editProfile: 'プロフィール編集',
    profileName: '名前',
    profilePhone: '電話番号',
    profileLang: '言語',
    profileSave: '保存',
    profileCancel: 'キャンセル',
    profileUpdated: 'プロフィールが更新されました',
    // Favorites
    myFavorites: 'お気に入り',
    noFavorites: 'お気に入りのショップはまだありません',
    // Filter
    filterPrice: '価格帯',
    filterRating: '最低評価',
    sortNewest: '新着順',
    sortPopular: '人気順',
    sortRating: '評価順',
    sortPrice: '価格順',
    sortDistance: '距離順',
    filterApply: '適用',
    filterReset: 'リセット',
    priceMin: '最低価格',
    priceMax: '最高価格',
    sortLabel: '並べ替え',
    filterLabel: 'フィルター',
    // Admin
    adminPanel: '管理パネル',
    backToApp: 'アプリへ戻る',
    adUsers: 'ユーザー',
    adShops: 'ショップ',
    adBookings: '予約',
    adSettlements: '精算',
    adStats: '統計',
    adRevenue: '売上',
    adReviews: 'レビュー',
    adAllRoles: '全ロール',
    adCustomer: '顧客',
    adOwner: 'オーナー',
    adAdmin: '管理者',
    adSearch: '検索...',
    adAll: '全て',
    adActive: '有効',
    adInactive: '無効',
    adName: '名前',
    adEmail: 'メール',
    adRole: 'ロール',
    adProvider: '認証方式',
    adCreated: '登録日',
    adAction: '操作',
    adOwnerCol: 'オーナー',
    adAddress: '住所',
    adStatus: 'ステータス',
    adMenu: 'メニュー',
    adTime: '日時',
    adPayment: '決済',
    adAmount: '金額',
    adShopCol: 'ショップ',
    adSales: '売上',
    adFee: '手数料',
    adPayments: '決済件数',
    adDeactivate: '無効化',
    adActivate: '有効化',
    adCancel: 'キャンセル',
    adAllStatus: '全ステータス',
    adPending: '保留',
    adConfirmed: '確定',
    adCompleted: '完了',
    adCancelled: 'キャンセル済',
    adNoshow: 'ノーショー',
    adCancelConfirm: 'この予約をキャンセルして返金しますか？',
    adTotalSales: '総売上',
    adTotalFee: '手数料',
    adSettlement: '精算額',
    adNoData: 'データなし',
    adNoSettlements: '精算データなし',
    adBookingStatus: '予約ステータス',
    adLast7Days: '過去7日間の予約',
    adPopularShops: '人気ショップ',
    adBookingsUnit: '件',
  },
  zh: {
    welcome: '欢迎来到 Glow Trip',
    email: '邮箱',
    password: '密码',
    name: '姓名',
    language: '语言',
    login: '登录',
    signup: '注册',
    logout: '退出登录',
    or: '或',
    noAccount: '没有账户？',
    hasAccount: '已有账户？',
    namePlaceholder: '请输入姓名',
    pwPlaceholder: '8个字符以上',
    searchPlaceholder: '搜索店铺...',
    dateTime: '日期和时间',
    requestLabel: '特殊要求（选填）',
    requestPlaceholder: '例：我是敏感肌肤...',
    bookNow: '立即预约',
    cancel: '取消',
    goOwnerDash: '进入店铺管理',
    goAdmin: '进入管理后台',
    navShops: '店铺',
    navBookings: '预约',
    navMy: '我的',
    myBookings: '我的预约',
    myPage: '个人中心',
    noShops: '未找到店铺',
    noBookings: '暂无预约',
    menu: '菜单',
    book: '预约',
    min: '分钟',
    role: '角色',
    lang: '语言',
    noName: '未设置姓名',
    confirmCancel: '确定要取消此预约吗？',
    bookingSuccess: '预约成功！',
    bookingFailed: '预约失败',
    selectDateTime: '请选择日期和时间',
    loginFailed: '登录失败',
    registerFailed: '注册失败',
    fillAll: '请填写所有字段',
    emailPwRequired: '请输入邮箱和密码',
    pwMin8: '密码至少需要8个字符',
    socialUnavailable: '不可用，请使用邮箱登录。',
    socialFailed: '社交登录失败',
    lineLoginFailed: 'LINE登录失败',
    shopDashboard: '店铺管理',
    backToApp: '返回应用',
    bookings: '预约列表',
    settlement: '结算',
    all: '全部',
    pending: '待处理',
    confirmed: '已确认',
    completed: '已完成',
    noshow: '未到店',
    cancelled: '已取消',
    noBookingsOwner: '暂无预约',
    noShopsRegistered: '暂无注册店铺',
    confirm: '确认',
    complete: '完成',
    noshowBtn: '未到店',
    cancelBtn: '取消',
    aiTranslation: 'AI翻译（韩语）',
    totalSales: '总销售额',
    settlementLabel: '结算额',
    fee: '手续费',
    amount: '金额',
    noSettlements: '暂无结算记录',
    shopInfo: '店铺信息',
    menuManage: '菜单管理',
    shopName: '店铺名称',
    shopAddress: '地址',
    shopPhone: '电话',
    shopDescription: '描述',
    save: '保存',
    saved: '已保存',
    addMenu: '添加菜单',
    menuTitle: '菜单名称',
    menuDesc: '描述',
    menuPrice: '价格（韩元）',
    menuDuration: '时长（分钟）',
    edit: '编辑',
    delete: '删除',
    confirmDelete: '确定要删除此菜单吗？',
    menuAdded: '菜单已添加',
    menuUpdated: '菜单已更新',
    menuDeleted: '菜单已删除',
    noMenus: '暂无菜单',
    active: '启用',
    inactive: '停用',
    shopImage: '店铺图片',
    menuImage: '菜单图片',
    uploadImage: '上传图片',
    changeImage: '更换图片',
    uploadFailed: '上传失败',
    pay: '立即支付',
    payAmount: '支付金额',
    cardInfo: '卡片信息',
    processing: '处理中...',
    paymentSuccess: '支付成功！',
    paymentFailed: '支付失败',
    paymentPending: '等待支付',
    refund: '退款',
    confirmRefund: '确定要退款吗？',
    refundSuccess: '退款成功',
    refundFailed: '退款失败',
    stripeNotReady: '正在加载支付系统...',
    noPayment: '无支付信息',
    mapView: '地图',
    listView: '列表',
    sortDistance: '按距离',
    sortDefault: '默认',
    km: 'km',
    locationPermission: '需要位置权限',
    loadingMap: '正在加载地图...',
    // Phase 12: Reviews
    reviews: '评价',
    writeReview: '写评价',
    rating: '评分',
    comment: '评论',
    commentPlaceholder: '服务怎么样？',
    submitReview: '提交评价',
    reviewSuccess: '评价提交成功',
    reviewFailed: '评价提交失败',
    noReviews: '暂无评价',
    avgRating: '平均评分',
    reviewCount: '条评价',
    // Phase 14: UI Renewal
    findBeauty: '在韩国找到属于你的美丽',
    navHome: '首页',
    navProfile: '我的',
    allCategories: '全部',
    popularClinics: '热门诊所',
    recommendedShops: '推荐',
    fromPrice: '起',
    cat_skincare: '护肤',
    cat_massage: '按摩',
    cat_facial: '面部护理',
    cat_waxing: '脱毛',
    cat_body: '身体护理',
    selectDate: '请选择日期',
    dayClosed: '当天休息',
    noSlots: '没有可预约的时间',
    bookingComplete: '预约已确认！',
    backToHome: '返回首页',
    refundPolicy: '确认后24小时前可免费取消。',
    schedule: '日程',
    openTime: '开始',
    closeTime: '结束',
    closed: '休息',
    saveSchedule: '保存日程',
    scheduleSaved: '日程已保存',
    favAdded: '已添加到收藏',
    favRemoved: '已从收藏中移除',
    // Profile
    editProfile: '编辑资料',
    profileName: '姓名',
    profilePhone: '电话',
    profileLang: '语言',
    profileSave: '保存',
    profileCancel: '取消',
    profileUpdated: '资料已更新',
    // Favorites
    myFavorites: '收藏店铺',
    noFavorites: '还没有收藏的店铺',
    // Filter
    filterPrice: '价格范围',
    filterRating: '最低评分',
    sortNewest: '最新',
    sortPopular: '热门',
    sortRating: '评分',
    sortPrice: '价格',
    sortDistance: '距离',
    filterApply: '应用',
    filterReset: '重置',
    priceMin: '最低价格',
    priceMax: '最高价格',
    sortLabel: '排序',
    filterLabel: '筛选',
    // Admin
    adminPanel: '管理面板',
    backToApp: '返回应用',
    adUsers: '用户',
    adShops: '店铺',
    adBookings: '预约',
    adSettlements: '结算',
    adStats: '统计',
    adRevenue: '营收',
    adReviews: '评价',
    adAllRoles: '所有角色',
    adCustomer: '顾客',
    adOwner: '店长',
    adAdmin: '管理员',
    adSearch: '搜索...',
    adAll: '全部',
    adActive: '启用',
    adInactive: '停用',
    adName: '姓名',
    adEmail: '邮箱',
    adRole: '角色',
    adProvider: '注册方式',
    adCreated: '注册日期',
    adAction: '操作',
    adOwnerCol: '店长',
    adAddress: '地址',
    adStatus: '状态',
    adMenu: '项目',
    adTime: '时间',
    adPayment: '支付',
    adAmount: '金额',
    adShopCol: '店铺',
    adSales: '销售额',
    adFee: '手续费',
    adPayments: '支付笔数',
    adDeactivate: '停用',
    adActivate: '启用',
    adCancel: '取消',
    adAllStatus: '全部状态',
    adPending: '待处理',
    adConfirmed: '已确认',
    adCompleted: '已完成',
    adCancelled: '已取消',
    adNoshow: '未到店',
    adCancelConfirm: '确定取消此预约并退款？',
    adTotalSales: '总销售额',
    adTotalFee: '手续费',
    adSettlement: '结算金额',
    adNoData: '暂无数据',
    adNoSettlements: '暂无结算记录',
    adBookingStatus: '预约状况',
    adLast7Days: '最近7天预约',
    adPopularShops: '热门店铺',
    adBookingsUnit: '笔',
  },
};

// ── Get / Set Language ─────────────────────────────────
function getLang() {
  return localStorage.getItem('glow_lang') || 'ko';
}

function setLang(lang) {
  localStorage.setItem('glow_lang', lang);
}

function t(key) {
  const lang = getLang();
  return (I18N[lang] && I18N[lang][key]) || I18N['en'][key] || key;
}

// ── Render Language Selector ───────────────────────────
function renderLangSelector(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;
  const current = getLang();
  const select = document.createElement('select');
  select.className = 'lang-selector';
  for (const [code, info] of Object.entries(LANGS)) {
    const opt = document.createElement('option');
    opt.value = code;
    opt.textContent = `${info.flag} ${info.label}`;
    if (code === current) opt.selected = true;
    select.appendChild(opt);
  }
  select.addEventListener('change', (e) => {
    setLang(e.target.value);
    location.reload();
  });
  container.innerHTML = '';
  container.appendChild(select);
}

// ── Apply i18n to DOM ──────────────────────────────────
function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    el.textContent = t(el.dataset.i18n);
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.dataset.i18nPlaceholder);
  });
}
