"""phase19 advanced booking and moderation

Revision ID: 7d40f731406e
Revises: cb1f6bacceae
Create Date: 2026-04-09 13:06:42.595421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d40f731406e'
down_revision = 'cb1f6bacceae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_devices_user_id'), ['user_id'], unique=False)

    op.create_table('slot_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'slot_time', name='uq_slot_hold_shop_time')
    )
    with op.batch_alter_table('slot_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_holds_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_holds_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_holds_slot_time'), ['slot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_holds_user_id'), ['user_id'], unique=False)

    op.create_table('special_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'date', name='uq_special_schedule_shop_date')
    )
    with op.batch_alter_table('special_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_special_schedules_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_special_schedules_shop_id'), ['shop_id'], unique=False)

    op.create_table('review_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'reporter_id', name='uq_review_report_once')
    )
    with op.batch_alter_table('review_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_reports_review_id'), ['review_id'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    with op.batch_alter_table('review_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_reports_review_id'))
        batch_op.drop_index(batch_op.f('ix_review_reports_reporter_id'))

    op.drop_table('review_reports')
    with op.batch_alter_table('special_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_special_schedules_shop_id'))
        batch_op.drop_index(batch_op.f('ix_special_schedules_date'))

    op.drop_table('special_schedules')
    with op.batch_alter_table('slot_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_holds_user_id'))
        batch_op.drop_index(batch_op.f('ix_slot_holds_slot_time'))
        batch_op.drop_index(batch_op.f('ix_slot_holds_shop_id'))
        batch_op.drop_index(batch_op.f('ix_slot_holds_expires_at'))

    op.drop_table('slot_holds')
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_devices_user_id'))

    op.drop_table('user_devices')
    # ### end Alembic commands ###
