"""add business_hours table

Revision ID: 855a2844e713
Revises: 9f0e296755a1
Create Date: 2026-04-06 11:53:56.046258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855a2844e713'
down_revision = '9f0e296755a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'day_of_week', name='uq_shop_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_hours')
    # ### end Alembic commands ###
